import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { decompress } from '../../src/extract/decompress';

/**
 * Parity test: our TS decompress() must byte-match CoilSnake's native decomp on
 * real ROM blocks. Fixtures are ROM-derived and gitignored (tools/_parity/),
 * generated by `tools/dump_decomp_fixtures.py`. When absent (CI, fresh clone
 * with no ROM) the suite is skipped rather than failed — the maintainer runs the
 * dumper locally against their own EarthBound.sfc to exercise it.
 *
 * Lives in test/ (not src/) so the browser-only app tsconfig never type-checks
 * its Node imports — same convention as test/overrides.test.ts.
 */
const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = resolve(here, '../../tools/_parity/decomp_fixtures.json');

type Fixture = { label: string; compressed: number[]; expected: number[] };

const fixtures: Fixture[] = existsSync(fixturePath)
  ? JSON.parse(readFileSync(fixturePath, 'utf8'))
  : [];

describe('eb decompress() parity with native CoilSnake', () => {
  it.skipIf(fixtures.length === 0)('has fixtures to test', () => {
    expect(fixtures.length).toBeGreaterThan(0);
  });

  for (const fx of fixtures) {
    it(`matches native output for ${fx.label}`, () => {
      const out = decompress(Uint8Array.from(fx.compressed), 0);
      expect(Array.from(out)).toEqual(fx.expected);
    });
  }
});
