// AbilityEditor — edit an entity's ranged PSI `abilities` list (enemy casts).
// Each ability carries a `mode` that selects its effect; the editor shows only
// the fields that mode uses. Mirrors server/npcSim.js sanitizeAbilities +
// EntityAbility (KEEP field names in sync). The caller persists via `onCommit`.
//
// Most abilities are canon-generated by tools/extract_enemy_afflictions.py; this
// lets a maintainer add/tune them by hand in the Entity Manager.

import { mkButton, mkSelect, mkNumberInput } from '../ui';
import { EntityAbility, EntityInflict } from '../../engine/EntityStats';
import { psiAnimIds } from '../../engine/PsiAnim';
import { buildInflictEditor, InflictEntry } from './InflictEditor';

type Mode = NonNullable<EntityAbility['mode']>;

const MODE_OPTIONS: { value: Mode; label: string }[] = [
  { value: 'offense', label: 'Offense — damage / status the player' },
  { value: 'heal', label: 'Heal — restore the caster’s HP' },
  { value: 'shield', label: 'Shield — caster blocks N hits' },
  { value: 'buff', label: 'Buff — raise a caster stat' },
  { value: 'debuff', label: 'Debuff — lower a player stat' },
  { value: 'magnet', label: 'Magnet — drain player PP' },
];

const BUFF_STAT_OPTIONS = [
  { value: 'offense', label: 'offense' },
  { value: 'defense', label: 'defense' },
  { value: 'speed', label: 'speed' },
];
const SHIELD_KIND_OPTIONS = [
  { value: 'physical', label: 'physical' },
  { value: 'psi', label: 'psi' },
];

// A sensible starting anim if none is authored yet, plus a fallback picker list
// when the PSI-anim catalog hasn't loaded.
const FALLBACK_ANIMS = [
  'psi_fire_alpha',
  'psi_freeze_alpha',
  'psi_thunder_alpha',
  'psi_flash_alpha',
  'psi_starstorm_alpha',
  'hypnosis_alpha',
  'paralysis_alpha',
  'brainshock_alpha',
  'lifeup_alpha',
  'healing_alpha',
  'shield_alpha',
  'psi_shield_alpha',
  'offense_up_alpha',
  'defense_down_alpha',
  'psi_magnet_alpha',
];

/** Fill in the fields a mode needs (leaving shared anim/range/cooldown alone),
 *  so switching mode never leaves an ability half-defined. */
function applyModeDefaults(a: EntityAbility, mode: Mode): void {
  a.mode = mode;
  // clear other-mode fields so the saved object stays clean
  for (const k of [
    'damage',
    'inflict',
    'heal',
    'buffStat',
    'buffAmt',
    'buffMs',
    'shieldKind',
    'shieldHits',
    'debuffStat',
    'debuffAmt',
    'debuffMs',
    'drainPp',
  ] as (keyof EntityAbility)[]) {
    delete a[k];
  }
  if (mode === 'offense') {
    a.damage = 20;
    a.inflict = [];
  } else if (mode === 'heal') {
    a.heal = 60;
  } else if (mode === 'shield') {
    a.shieldKind = 'physical';
    a.shieldHits = 4;
  } else if (mode === 'buff') {
    a.buffStat = 'offense';
    a.buffAmt = 20;
    a.buffMs = 20000;
  } else if (mode === 'debuff') {
    a.debuffStat = 'defense';
    a.debuffAmt = 15;
    a.debuffMs = 15000;
  } else if (mode === 'magnet') {
    a.drainPp = 10;
  }
}

export interface AbilityEditorOpts {
  entries: EntityAbility[];
  onCommit: (list: EntityAbility[]) => void;
}

export function buildAbilityEditor(opts: AbilityEditorOpts): HTMLDivElement {
  const list: EntityAbility[] = opts.entries.map((a) => ({
    ...a,
    inflict: a.inflict?.map((i) => ({ ...i })),
  }));
  const commit = () => opts.onCommit(list);
  const animIds = psiAnimIds();
  const animOptions = (animIds.length ? animIds : FALLBACK_ANIMS).map((v) => ({
    value: v,
    label: v,
  }));

  const wrap = document.createElement('div');
  wrap.style.cssText =
    'display:flex;flex-direction:column;gap:6px;border-top:1px solid #2a3540;padding-top:6px;';
  const head = document.createElement('div');
  head.textContent = 'PSI ABILITIES (ranged casts)';
  head.style.cssText = 'color:#b06de8;font-size:11px;';
  wrap.appendChild(head);

  const rowsEl = document.createElement('div');
  rowsEl.style.cssText = 'display:flex;flex-direction:column;gap:8px;';
  wrap.appendChild(rowsEl);

  const numField = (
    parent: HTMLElement,
    label: string,
    value: number | undefined,
    onSet: (n: number) => void,
    o: { min?: number; max?: number; width?: number; tip?: string } = {}
  ) => {
    const r = document.createElement('div');
    r.style.cssText = 'display:flex;align-items:center;gap:5px;';
    const l = document.createElement('span');
    l.textContent = label;
    l.style.cssText = 'width:82px;color:#9fb8cc;font-size:11px;';
    if (o.tip) l.title = o.tip;
    r.appendChild(l);
    const inp = mkNumberInput({
      value,
      width: o.width ?? 64,
      min: o.min ?? 0,
      max: o.max,
      tip: o.tip,
      onChange: (v, el) => {
        const n = v ?? o.min ?? 0;
        el.value = String(n);
        onSet(n);
        commit();
      },
    });
    r.appendChild(inp);
    parent.appendChild(r);
  };

  const selField = (
    parent: HTMLElement,
    label: string,
    options: { value: string; label: string }[],
    value: string,
    onSet: (v: string) => void
  ) => {
    const r = document.createElement('div');
    r.style.cssText = 'display:flex;align-items:center;gap:5px;';
    const l = document.createElement('span');
    l.textContent = label;
    l.style.cssText = 'width:82px;color:#9fb8cc;font-size:11px;';
    r.appendChild(l);
    r.appendChild(
      mkSelect(options, {
        value,
        flex: true,
        onChange: (v) => {
          onSet(v);
          commit();
        },
      })
    );
    parent.appendChild(r);
  };

  const renderRows = () => {
    rowsEl.innerHTML = '';
    list.forEach((a, idx) => {
      const card = document.createElement('div');
      card.style.cssText =
        'display:flex;flex-direction:column;gap:4px;border:1px solid #2a3540;border-radius:4px;padding:6px;';

      // header: mode + remove
      const hdr = document.createElement('div');
      hdr.style.cssText = 'display:flex;align-items:center;gap:5px;';
      hdr.appendChild(
        mkSelect(MODE_OPTIONS, {
          value: a.mode ?? 'offense',
          flex: true,
          tip: 'What this cast does.',
          onChange: (v) => {
            applyModeDefaults(a, v as Mode);
            commit();
            renderRows();
          },
        })
      );
      mkButton(
        '🗑',
        () => {
          list.splice(idx, 1);
          commit();
          renderRows();
        },
        {
          parent: hdr,
          pad: '1px 6px',
          tip: 'Remove this ability.',
        }
      );
      card.appendChild(hdr);

      // shared: anim, range, cooldown
      selField(
        card,
        'anim',
        animOptions,
        a.anim ?? animOptions[0]?.value ?? '',
        (v) => (a.anim = v)
      );
      numField(card, 'range px', a.range, (n) => (a.range = n), { min: 16, max: 600 });
      numField(card, 'cooldown ms', a.cooldownMs, (n) => (a.cooldownMs = n), {
        min: 300,
        max: 30000,
        width: 74,
      });

      // mode-specific
      const mode = a.mode ?? 'offense';
      if (mode === 'offense') {
        numField(card, 'damage', a.damage, (n) => (a.damage = n), { min: 0, max: 9999 });
        // optional status procs on the cast (Hypnosis/Paralysis/Brainshock)
        card.appendChild(
          buildInflictEditor({
            entries: (a.inflict ?? []) as InflictEntry[],
            onCommit: (l) => {
              a.inflict = l as EntityInflict[];
              commit();
            },
            emptyText: 'no status on this cast (pure damage)',
            addChance: 60,
            noun: 'cast',
          })
        );
      } else if (mode === 'heal') {
        numField(card, 'heal HP', a.heal, (n) => (a.heal = n), { min: 1, max: 9999 });
      } else if (mode === 'shield') {
        selField(
          card,
          'shield kind',
          SHIELD_KIND_OPTIONS,
          a.shieldKind ?? 'physical',
          (v) => (a.shieldKind = v as 'physical' | 'psi')
        );
        numField(card, 'hits', a.shieldHits, (n) => (a.shieldHits = n), { min: 1, max: 20 });
      } else if (mode === 'buff') {
        selField(card, 'stat', BUFF_STAT_OPTIONS, a.buffStat ?? 'offense', (v) => (a.buffStat = v));
        numField(card, 'amount', a.buffAmt, (n) => (a.buffAmt = n), { min: 1, max: 999 });
        numField(card, 'duration ms', a.buffMs, (n) => (a.buffMs = n), {
          min: 1000,
          max: 120000,
          width: 74,
        });
      } else if (mode === 'debuff') {
        selField(
          card,
          'player stat',
          BUFF_STAT_OPTIONS,
          a.debuffStat ?? 'defense',
          (v) => (a.debuffStat = v)
        );
        numField(card, 'amount', a.debuffAmt, (n) => (a.debuffAmt = n), { min: 1, max: 999 });
        numField(card, 'duration ms', a.debuffMs, (n) => (a.debuffMs = n), {
          min: 1000,
          max: 120000,
          width: 74,
        });
      } else if (mode === 'magnet') {
        numField(card, 'PP drained', a.drainPp, (n) => (a.drainPp = n), { min: 1, max: 999 });
      }

      rowsEl.appendChild(card);
    });
    if (!list.length) {
      const none = document.createElement('div');
      none.textContent = 'none — this entity casts no PSI';
      none.style.cssText = 'color:#667;font-size:10px;';
      rowsEl.appendChild(none);
    }
  };
  renderRows();

  mkButton(
    '+ Add PSI ability',
    () => {
      const a: EntityAbility = {
        anim: animOptions[0]?.value ?? 'psi_fire_alpha',
        range: 240,
        cooldownMs: 3000,
      };
      applyModeDefaults(a, 'offense');
      list.push(a);
      commit();
      renderRows();
    },
    { parent: wrap, tip: 'Add a ranged PSI cast this entity uses.' }
  );

  return wrap;
}
